# Generated by Django 4.0.3 on 2022-04-19 06:50

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budget_choices',
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(default='dfsdf', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 6, 49, 58, 948527, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default='okay', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='saving',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 6, 50, 16, 418927, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.DeleteModel(
            name='BudgetChoices',
        ),
    ]
