# Generated by Django 4.0.3 on 2022-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_budget_choices_budget_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='saving',
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
