# Generated by Django 4.0.3 on 2022-04-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget')),
            ],
        ),
    ]
