# Generated by Django 4.0.3 on 2022-04-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_saving_delete_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='saving',
        ),
    ]
