# Generated by Django 4.0.3 on 2022-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='expenses_title',
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='expenses',
            name='desciption',
            field=models.CharField(default='jjdjd', max_length=300),
            preserve_default=False,
        ),
    ]
