# Generated by Django 4.0.3 on 2022-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_desciption_expenses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
